name: macos

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  mac_windows:
    name: "${{ matrix.os }} v${{ matrix.perl-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: ["macos-latest", "windows-latest"]
        os: ["macos-latest"]
        perl-version:
          - "5.10"
          - "5.12"
          - "5.14"
          - "5.16"
          - "5.18"
          - "5.20"
          - "5.22"
          - "5.24"
          - "5.26"
          - "5.28"
          - "5.30"    
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    steps:
      - uses: actions/checkout@v2
      - name: Set Up Perl
        uses: shogo82148/actions-setup-perl@v1.3.0
        with:
          perl-version: ${{ matrix.perl-version }}
      - uses: actions/download-artifact@master
        with:
          name: build_dir
          path: .
      - run: perl -V
      #- run: cpanm --installdeps .
      - name: install deps using cpm
        uses: perl-actions/install-with-cpm@v1.3
        with:
          install: |
            B::COW
          sudo: false      
      - run: perl Makefile.PL
      - run: make test
